# Generated by Django 4.0.1 on 2022-01-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gussed',
            new_name='guessed_word',
        ),
    ]
